[config.defaults]
image_viewer = ""
image_viewer_cui = ""
iv_cmds = {}
image_width = 0
system_cmd = ""
system_cmd_args = ["%c", "%s"]
timezone = ""
date_format = "%x-%X (%Z)"
pp_kwargs = {compact = true}
numpy_printoptions = {threshold = 300}
cui_linenumber = false
cui_wrap = false
[config.pickle]
encoding = "ASCII"
[config.jupyter]
show_number = false
encoding = "utf-8"
syntax_highlight = true
language = ""
highlight_style = "default"

[colors.defaults]
msg_error = ["r", ""]
msg_warn = ["y", ""]
msg_key_name = ["k", "y"]
interactive_path = ["", "c"]
interactive_contents = ["", "g"]
interactive_output = ["", "r"]
cui_main = ["w", "k"]
cui_top = ["w", "g"]
cui_left = ["w", "b"]
cui_error = ["r", "k"]
cui_search = ["w", "m"]
cui_file_info = ["y", "k"]
cui_dir_index = ["g", "w"]
cui_file_index = ["m", "w"]
[colors.jupyter]
input_color = ["c", ""]
output_color = ["r", ""]
type_color = ["g", ""]

